#ifndef NODE_OPCODE_DEFINE
#error "Please define NODE_OPCODE_DEFINE before including NodeOpCodes.h"
#else
#if defined(NODE_OPCODE_DEFINE_SUPPORT) || defined(NODE_OPCODE_DEFINE_ALL)
// NODE_OPCODE_DEFINE(Unknown)
NODE_OPCODE_DEFINE(Constant)
NODE_OPCODE_DEFINE(Scope)
NODE_OPCODE_DEFINE(Projection)
#endif
#if defined(NODE_OPCODE_DEFINE_BIN) || defined(NODE_OPCODE_DEFINE_ALL)
NODE_OPCODE_DEFINE(Add)
NODE_OPCODE_DEFINE(Sub)
NODE_OPCODE_DEFINE(Mul)
NODE_OPCODE_DEFINE(Div)
NODE_OPCODE_DEFINE(Mod)
NODE_OPCODE_DEFINE(Lsh)
NODE_OPCODE_DEFINE(Rsh)
NODE_OPCODE_DEFINE(And)
NODE_OPCODE_DEFINE(Or)
#endif
#if defined(NODE_OPCODE_DEFINE_CMP) || defined(NODE_OPCODE_DEFINE_ALL)
NODE_OPCODE_DEFINE(Eq)
NODE_OPCODE_DEFINE(NotEq)
NODE_OPCODE_DEFINE(Lt)
NODE_OPCODE_DEFINE(Gt)
NODE_OPCODE_DEFINE(Leq)
NODE_OPCODE_DEFINE(Geq)
#endif
#if defined(NODE_OPCODE_DEFINE_UNARY) || defined(NODE_OPCODE_DEFINE_ALL)
NODE_OPCODE_DEFINE(Not)
NODE_OPCODE_DEFINE(Neg)
#endif
#if defined(NODE_OPCODE_DEFINE_CONTROL) || defined(NODE_OPCODE_DEFINE_ALL)
NODE_OPCODE_DEFINE(Start)
NODE_OPCODE_DEFINE(Return)
NODE_OPCODE_DEFINE(Stop)
#endif
#endif
